# Generated by Neurodocker and Reproenv.

FROM mambaorg/micromamba:1.4.3-jammy

COPY --chown=$MAMBA_USER:$MAMBA_USER env.yml /tmp/env.yml
COPY --chown=$MAMBA_USER:$MAMBA_USER pyproject.toml README.md src /tmp/biomarkers/

# need to install python first for fsl installer (env handled by some python packages)
# # (otherwise python will not be found)
ENV TZ=Europe/London
RUN micromamba install -q --name base --yes --file /tmp/env.yml \
    && micromamba run -qn base pip install --no-deps /tmp/biomarkers/ \
    && rm -rf /tmp/biomarkers /tmp/env.yml \
    && micromamba clean --yes --all

# Best practices ? (https://github.com/nipreps/mriqc/blob/master/Dockerfile)
# USER root
# RUN ldconfig
# USER $MAMBA_USER

COPY --chown=$MAMBA_USER:$MAMBA_USER tools/fslinstaller.py /tmp/
RUN micromamba run -n base python /tmp/fslinstaller.py -d /opt/fsl \
    && rm /tmp/fslinstaller.py

# Unless otherwise specified each process should only use one thread - nipype
# will handle parallelization
ENV MKL_NUM_THREADS=1 
ENV OMP_NUM_THREADS=1

ENV FSLDIR=/opt/fsl
ENV FSLOUTPUTTYPE=NIFTI_GZ

ENV PATH="${FSLDIR}/share/fsl/bin:${PATH}"

ENV PREFECT_HOME=/tmp/prefect
ENV PREFECT_LOCAL_STORAGE_PATH="${PREFECT_HOME}/storage"
ENV PREFECT_API_DATABASE_CONNECTION_URL="sqlite+aiosqlite:///${PREFECT_HOME}/orion.db"
ENV PREFECT_API_DATABASE_CONNECTION_TIMEOUT=1200
ENV PREFECT_API_DATABASE_TIMEOUT=1200
ENV PREFECT_API_REQUEST_TIMEOUT=2400

