# Generated by Neurodocker and Reproenv.

FROM mambaorg/micromamba:1.4.2-jammy

COPY --chown=$MAMBA_USER:$MAMBA_USER env.yml /tmp/env.yml
COPY --chown=$MAMBA_USER:$MAMBA_USER pyproject.toml README.md src /tmp/biomarkers/

# need to install python first for fsl installer (env handled by some python packages)
# # (otherwise python will not be found)
ENV MAMBA_DOCKERFILE_ACTIVATE=1 
RUN micromamba install --name base --yes --file /tmp/env.yml --verbose \
    && pip install --no-deps /tmp/biomarkers/ \
    && rm -rf /tmp/biomarkers /tmp/env.yml \
    && micromamba clean --yes --all

ENV FSLDIR=/opt/conda \
    FSLOUTPUTTYPE=NIFTI_GZ

# Best practices ? (https://github.com/nipreps/mriqc/blob/master/Dockerfile)
# USER root
# RUN ldconfig
# USER $MAMBA_USER

# Unless otherwise specified each process should only use one thread - nipype
# will handle parallelization
ENV MKL_NUM_THREADS=1 \
    OMP_NUM_THREADS=1

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]
# CMD ["--help"]

