#!/bin/bash
#SBATCH -J mark
#SBATCH -o out
#SBATCH -e err
#SBATCH -t 05:00:00
#SBATCH -p corralextra
#SBATCH -N 1 -n 1
#SBATCH -A A2CPS

date

source "$HOME"/.bashrc

# due to WAL https://sqlite.org/wal.html
# db must be on the same filesystem
export PREFECT_HOME=/tmp/prefect
export PREFECT_LOCAL_STORAGE_PATH="${PREFECT_HOME}/storage"
export PREFECT_ORION_DATABASE_CONNECTION_URL='sqlite+aiosqlite:///${PREFECT_HOME}/orion.db'
export PREFECT_ORION_DATABASE_CONNECTION_TIMEOUT=60
#export PREFECT_ORION_DATABASE_TIMEOUT=60

#prefect_old=/corral-secure/projects/A2CPS/shared/psadil/jobs/mark/prefect
#if [[ -d $prefect_old ]]; then
#  mkdir ${PREFECT_HOME}
#  rsync -a ${prefect_old}/ ${PREFECT_HOME}/
#else
#  mkdir ${prefect_old}
#fi

mamba activate biomarkers

set -x

export FSLOUTPUTTYPE=NIFTI_GZ
export FSLDIR=/work2/08266/psadil/mambaforge/envs/biomarkers

catdir=/corral-secure/projects/A2CPS/shared/psadil/products/mris/all_sites/cat
bidsdir=/corral-secure/projects/A2CPS/products/mris/all_sites/bids
outdir=/corral-secure/projects/A2CPS/shared/psadil/jobs/mark/biomarkers
rest_dir=/corral-secure/projects/A2CPS/shared/psadil/products/mris/all_sites/fmriprep/rest
cuff_dir=/corral-secure/projects/A2CPS/shared/psadil/products/mris/all_sites/fmriprep/cuff

# link cat
date

shopt -s extglob

# for site in NS_northshore UI_uic UC_uchicago UM_umichigan WS_wayne_state SH_spectrum_health; do
#   # cp -aRust ${catdir} /corral-secure/projects/A2CPS/products/mris/${site}/cat12/*/!(*err|*out|launchfile)
#   rsync -a \
#   --exclude="*err" \
#   --exclude="*out" \
#   --exclude="launchfile" \
#   /corral-secure/projects/A2CPS/products/mris/${site}/cat12/*/ \
#   ${catdir}
# done

# # link fmriprep

# for site in NS_northshore UI_uic UC_uchicago UM_umichigan WS_wayne_state SH_spectrum_health; do
#   # cp -aRust ${fmriprep_dir} /corral-secure/projects/A2CPS/products/mris/${site}/fmriprep/*/rest/fmriprep/!(*html|json|.bidsignore|*tsv|*json|logs)
#   rsync -a \
#   --exclude="*logs*" \
#   --exclude=".bidsignore" \
#   --exclude="*err" \
#   --exclude="*out" \
#   --exclude="*html" \
#   --exclude="*json" \
#   --exclude="*tsv" \
#   /corral-secure/projects/A2CPS/products/mris/${site}/fmriprep/*/rest/fmriprep/ \
#   ${rest_dir}

#   rsync -a \
#   --exclude="*logs*" \
#   --exclude=".bidsignore" \
#   --exclude="*err" \
#   --exclude="*out" \
#   --exclude="*html" \
#   --exclude="*json" \
#   --exclude="*tsv" \
#   /corral-secure/projects/A2CPS/products/mris/${site}/fmriprep/*/cuff/fmriprep/ \
#   ${cuff_dir}

# done
# grab extras from arbitrary source
#asource=/corral-secure/projects/A2CPS/products/mris/SH_spectrum_health/fmriprep/SH20135V1/rest/fmriprep
#cp -aRust ${fmriprep_dir} ${asource}/.bidsignore ${asource}/*json ${asource}/*tsv ${asource}/logs

date 

# mark --output-dir ${outdir} --cat-dir ${catdir} --bids-dir ${bidsdir} --fmriprep-dir ${fmriprep_dir} 
#mark --output-dir ${outdir} --cuff-dir ${cuff_dir} 
# mark --output-dir ${outdir} --rest-dir ${rest_dir} 
mark --output-dir ${outdir} --rest-dir ${rest_dir} --cuff-dir ${cuff_dir} 

date

#rsync -a ${PREFECT_HOME}/ ${prefect_old}/